config/routes.rb
LanguageLearningCommons::Application.routes.draw do

	root to: 'application#welcome'

  devise_for :users , :controllers =>
    { :registrations => "registrations"}

  resources :users, :only => [:show] do
    resources :knowings, :only => [:show]
    resources :learnings, :only => [:show]
    resources :buddyships, :only => [:index]
    resources :notes, :only => [:new, :create, :show, :index] do
      resources :marks, :only => [:create]
    end
  end

  resources :languages, :only => [:show, :index]
  resources :buddyships, :only => [:create, :destroy]
  resources :buddyship_proposals, :only => [:create, :destroy]
  resources :note_demos, :only => [:create]
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :author, :author_id, :language, :language_id, :title, :body

  belongs_to :author, :class_name => 'User'
  belongs_to :language
  has_many :marks

  validates :author, :title, :body, :presence => true
  validates :title, :uniqueness => {:scope => :author_id}
  # cannot .build notes due to preceeding line (author_id will be missing)
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @author = current_user
    @author_id = @author.id
    @note = Note.new
    render :no_learning_languages if @author.learning_languages.none?
  end

  def create
    @note = Note.create(params[:note])
    if @note.save
      redirect_to user_note_url(@note.author_id, @note)
    else
      flash[:error] = "Note publication failed."
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
    @author = @note.author
    @self_page = @note.author == current_user
  end

  def index
    @author = User.find(params[:user_id])
    @self_page = @author == current_user
    @notes_by_language = @author.notes_by_language
    @suggestion_language = @author.suggestion_language
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/index.html.erb
<div class="row">
  <div class="span12">
    <div class="userName bigTitle">
      <%= link_to @author.name, user_url(@author) %>'s Notes
    </div>
    <% if @notes_by_language[:noted].none? %>
      <br>
      <%= @self_page ? "You haven't" : (@author.name + " hasn't") %>
        written any notes yet.
      <% if @self_page %>
        <br><br>
        <span class="languageList">
          <% if @suggestion_language && @suggestion_language[:type] == :learning %>
            Why not
              <%= link_to ("write one in " + @suggestion_language[:language].name), new_user_note_url %>?
          <% else %>
            <%= link_to "Pick a learning language first.",
                        edit_user_registration_url %>
          <% end %>
        </span>
      <% end %>
    <% else %>
      <% @notes_by_language[:noted].each_pair do |language, language_notes| %>
        <div class="languageList">
          In
          <span class="languageName">
            <%= link_to language.name, language_url(language) %>
          </span>
        </div>
        <ul>
          <% language_notes.each do |language_note| %>
            <span class="noteTitle"
            <%= language.name == 'Arabic' ? ' dir="rtl"' : ''%>>
              <%= link_to language_note.title, user_note_url(@author, language_note) %>
            </span>
            <span class="faint">
              - <%= time_ago_in_words (language_note.created_at) %> ago
            </span>
            <br />
          <% end %>
        </ul>
      <% end %>
      <% @notes_by_language[:noteless].each do |language| %>
        <br> 
        <!-- before adding line breaks check state: 1 noted langauge, 1 noteless -->
        <font color="gray">
          <%= @self_page ? "You haven't" : (@author.name + " hasn't") %>
          written any notes in
          <span class="languageName">
            <%= link_to language.name, language_url(language) %>
          </span>
          yet.
        </font>
        <br>
      <% end %>
      <% if @self_page %>
        <br>
        <span class="noteTitle">
          <%= link_to "Write a new note", new_user_note_url %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="row">
  <div class="span12">
    <h1>New Note</h1>
    <%= form_for @note, :url => "/users/#{@author.id}/notes" do |f|%>
      <div class="row">
        <div class="span6">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="span6">
          <%= f.label :language_id, "Language" %>
          <%= f.collection_select :language_id, @author.learning_languages,
                                  :id, :name %>
        </div>
      </div>
      <br>

      <%= f.label :body %>
      <%= f.text_area :body, :style => "width: 700px; height: 150px;"%>
      <br>
      <%= hidden_field_tag "note[author_id]", @author.id %>
      <%= f.submit "Publish" %>
    <% end %>
  </div>
</div>

app/views/notes/no_learning_languages.html.erb
<div class="row">
  <div class="span12">
    <h4>You are not currently learning any languages.</h4>
    <div>In order to write a note in a language you must first indicate that you are learning it.</div>
    <br>
    <%= link_to "OK", user_url(@author) %>
  </div>
</div>


app/views/notes/show.html.erb
<div class="row">
  <div class="span12">
    <h3>
      <span class="noteTitle">
        <%= link_to (@author.name + "'s Notes"), user_notes_url(@author) %>
      </span>
    </h3>
    In
    <span class="languageName">
      <%= link_to @note.language.name, language_url(@note.language) %>
    </span>
    <br><br>
    <div class="noteShowView"></div>

    <script type="text/javascript">
      <% if ! @self_page && current_user.known_languages.include?(@note.language) %>
        $(LLC.showRevisableNote(<%= Note.where(:id => @note.id)
          .includes(:marks)
          .to_json(:include => :marks)
          .html_safe %>, $('.noteShowView')));
      <% else %>
        $(LLC.showNote(<%= Note.where(:id => @note.id)
          .includes(:marks)
          .to_json(:include => :marks)
          .html_safe %>, $('.noteShowView')));
      <% end %>
    </script>
  </div>
</div>