config/routes.rb
LanguageLearningCommons::Application.routes.draw do

	root to: 'application#welcome'

  devise_for :users , :controllers =>
    { :registrations => "registrations"}

  resources :users, :only => [:show] do
    resources :knowings, :only => [:show]
    resources :learnings, :only => [:show]
    resources :buddyships, :only => [:index]
    resources :notes, :only => [:new, :create, :show, :index] do
      resources :marks, :only => [:create]
    end
  end

  resources :languages, :only => [:show, :index]
  resources :buddyships, :only => [:create, :destroy]
  resources :buddyship_proposals, :only => [:create, :destroy]
  resources :note_demos, :only => [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  attr_accessible :name, :login, :email, :password, :demo,
                  :password_confirmation, :remember_me,
                  :known_language_ids, :learning_language_ids

  # Users know languages
	has_many :knowings
	has_many :known_languages, :through => :knowings, :source => :language

  # Users are learning languages
	has_many :learnings
	has_many :learning_languages, :through => :learnings, :source => :language

  # A "buddyship" (as in "friendship") is represented redundantly by two matching
  # rows in the same table, each representing one user's role as a buddy to the
  # the other user.
  has_many :buddied_roles, :class_name => 'Buddyship'
  has_many :buddies, :through => :buddied_roles

  has_many :buddy_roles, :class_name => 'Buddyship', :foreign_key => 'buddy_id'

  # When one user attempts to "bebuddy" (as in "befriend") another, a
  # BuddyshipProposal is created. The target user either accepts it
  # (creating a buddyship) or rejects it (destroying it).
  has_many :sent_buddyship_proposals, :class_name => 'BuddyshipProposal',
                                      :foreign_key => 'proposing_user_id'
  has_many :received_buddyship_proposals, :class_name => 'BuddyshipProposal',
                                      :foreign_key => 'target_user_id'

  # Users write notes in learning languages as practice.
  has_many :notes, :foreign_key => :author_id

  # Users may make revisions to and may comment on notes other users have written
  # in languages they know.
  has_many :marks, :foreign_key => :marker_id

  before_save :capitalize_name

  validates :name, :email, :presence => true
  validates :password, :presence => true, :on => :create
  validates :name, :email, :uniqueness => true

  def capitalize_name
    self.name = self.name.capitalize
  end

  # Adds both buddyship entries at once.
  def bebuddy(other_user)
    Buddyship.transaction do
      Buddyship.create(user_id: self.id, buddy_id: other_user.id)
      Buddyship.create(user_id: other_user.id, buddy_id: self.id)
    end
  end

  # And removes them.
  def unbuddy(other_user)
    Buddyship.transaction do
      Buddyship.where(user_id: self.id, buddy_id: other_user.id).first.destroy
      Buddyship.where(user_id: other_user.id, buddy_id: self.id).first.destroy
    end
  end

  # I replaced validations in the knowing and learning models with this method
  # which guarentees the uniqueness of user-language relationships but checks
  # a set of changes as a whole, so they won't be invalid based on old values
  # I intend to only update languages through this method, but how to enforce that?
  def update_langauges(language_ids)
    transaction do
      language_ids[:known_language_ids].each do |known_lang|
        if language_ids[:learning_language_ids].include?(known_lang)
          raise "Users cannot both know and be learning a language."
        end
      end
      self.learning_language_ids = language_ids[:known_language_ids]
      self.learning_language_ids = language_ids[:learning_language_ids]
    end
  end

  # Used to suggest user actions for a new account.
  def suggestion_language
    if self.known_languages.none? && self.learning_languages.none?
        nil
    elsif self.learning_languages.any?
        {:type => :learning,
         :language => self.learning_languages.first}
    else
      {:type => :known,
       :language => self.known_languages.first}
    end
  end

  # I'm currently only using this in NotesController#index
  # Worthwhile?
  def notes_by_language
    notes_by_language = {:noted => {}, :noteless => []}
    self.learning_languages.each do |learning_language|
      language_notes = notes.where(language_id: learning_language.id)
      if language_notes.any?
        notes_by_language[:noted][learning_language] = language_notes
      else
        notes_by_language[:noteless] << learning_language
      end
    end
    notes_by_language
  end

# below as per https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value",
                              { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    # default to current_user (root routes here)
    @user = params[:id].nil? ? current_user : User.find(params[:id])

    @self_page = @user == current_user
    @is_buddy = current_user.buddies.include?(@user)
		@knowings = @user.knowings
		@learnings = @user.learnings
    @notes = @user.notes
    @buddyship_proposal = BuddyshipProposal
      .where(proposing_user_id: @user.id, target_user_id: current_user.id).first
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buddyship_proposal.html.erb
<span class="buddyName">
  <%= link_to buddyship_proposal.proposing_user.name,
      user_url(buddyship_proposal.proposing_user) %>
      wants to be your buddy! <br>
</span>
<%= form_tag "/buddyships", :method => "post" do %>
  <%= hidden_field_tag :id, buddyship_proposal.proposing_user.id %>
  <%= submit_tag "Accept" %>
<% end %>
<%= form_tag ('/buddyship_proposals/' +
  "#{buddyship_proposal.proposing_user.id}"), :method => "delete" do %>
  <%= submit_tag "Reject" %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class ="span12 bigTitle">
    <%= @user.name %>
  </div>
</div>
<div class="row">
  <div class ="span12">
    <% unless @self_page %>
      <%= render 'layouts/bebuddy_button', :locals =>
        { :user => @user,
          :buddyship_proposal => @buddyship_proposal,
          :is_buddy => @is_buddy } %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class ="span12 languageList" id="knownLanguageList">
  	 <% if @knowings.any? %>
        Knows
      	<%= @knowings.map do |knowing| %>
          <% '<span class="languageName">' +
            (link_to knowing.language.name, language_url(knowing.language)) +
          '</span>' %>
      	<% end.join(", ").html_safe %>
  	<% else %>
  		<%= link_to "What language(s) do you know?", edit_user_registration_path %>
  	<% end %>
  </div>
</div>
<div class="row">
  <div class ="span12 languageList" id="learningLanguageList">
  	<% if @learnings.any? %>
  	  Learning
      <%= @learnings.map do |learning| %>
        <% '<span class="languageName">' +
          (link_to learning.language.name, language_url(learning.language)) +
        '</span>' %>
  		<% end.join(", ").html_safe %>
    <% else %>
  		<%= link_to "What language(s) are you learning?",
       edit_user_registration_path %>
  	<% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="span6">
    <span class="noteTitle listTitle">
      <%= link_to "Notes", user_notes_url(@user) %>
    </span>
    <span class="faint">(<%= @notes.count %>)</span>
    <br><br>
  	<% if @learnings.any? %>
  			<ul>
  				<% @notes.each do |note| %>
  					<span class="noteTitle"
              <%= note.language.name == 'Arabic' ? ' dir="rtl"' : ''%>>
              <%= link_to note.title, user_note_url(@user.id, note) %>
            </span>
            <span class="faint">
              - <%= time_ago_in_words (note.created_at) %> ago
            </span>
            <br>
  				<% end %>
          <br>
          <span class="noteTitle">
            <%= link_to "New note", new_user_note_url(@user) if @self_page%>
          </span>
  			</ul>
  	<% end %>
  </div>
  <div class="span5">
    <span class="userName listTitle">
      <%= link_to "Buddies", user_buddyships_url(@user) %>
    </span>
    <span class="faint">(<%= @user.buddies.count %>)</span>
    <br><br>
    <ul>
      <% @user.buddies.each do |buddy| %>
        <span class="userName">
          <%= link_to buddy.name, user_url(buddy) %>
        </span>
        <br>
      <% end %>
      <% if @self_page && @user.received_buddyship_proposals.any? %>
        <br>
        <% @user.received_buddyship_proposals.each do |buddyship_proposal| %>
          <%= render :partial => 'layouts/buddyship_proposal',
            :locals => {:buddyship_proposal => buddyship_proposal} %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>