config/routes.rb
LanguageLearningCommons::Application.routes.draw do

	root to: 'application#welcome'

  devise_for :users , :controllers =>
    { :registrations => "registrations"}

  resources :users, :only => [:show] do
    resources :knowings, :only => [:show]
    resources :learnings, :only => [:show]
    resources :buddyships, :only => [:index]
    resources :notes, :only => [:new, :create, :show, :index] do
      resources :marks, :only => [:create]
    end
  end

  resources :languages, :only => [:show, :index]
  resources :buddyships, :only => [:create, :destroy]
  resources :buddyship_proposals, :only => [:create, :destroy]
  resources :note_demos, :only => [:create]
end

app/views/layouts/_bebuddy_button.html.erb
<% if @is_buddy %>
  <%= "You are study buddies with #{@user.name}" %>
  <%= form_tag "/buddyships/#{@user.id}", :method => "delete" do %>
    <%= submit_tag "Unbuddy" %>
  <% end %>
<% else %>
  <% if @buddyship_proposal %>
    <%= render :partial => 'layouts/buddyship_proposal',
               :locals => {:buddyship_proposal => @buddyship_proposal} %>
  <% else %>
    <%= form_tag "/buddyship_proposals", :method => "post" do %>
      <%= hidden_field_tag :id, @user.id %>
      <%= submit_tag "Bebuddy" %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_buddyship_proposal.html.erb
<span class="buddyName">
  <%= link_to buddyship_proposal.proposing_user.name,
      user_url(buddyship_proposal.proposing_user) %>
</span>
wants to be your buddy! <br>
<%= form_tag "/buddyships", :method => "post", :class => 'form-inline' do %>
  <%= hidden_field_tag :id, buddyship_proposal.proposing_user.id %>
  <%= submit_tag "Accept" %>
<% end %>

<%= form_tag ('/buddyship_proposals/' +
  "#{buddyship_proposal.proposing_user.id}"), :method => "delete", :class => 'form-inline' do %>
  <%= submit_tag "Reject" %>
<% end %>
<div class="clearDiv"></div>


app/views/layouts/_create_demo_user_button.html.erb
<%= form_tag '/users/', :method => :post do %>
	<% name = demo_user_name %>
	<%= hidden_field_tag 'user[name]', name %>
	<%= hidden_field_tag 'user[email]', (name + "@example.com") %>
	<%= hidden_field_tag 'user[password]', '123123123' %>
	<%= hidden_field_tag 'user[password_confirmation]', '123123123' %>
	<%= hidden_field_tag 'user[demo]', true %>
	<%= hidden_field_tag 'commit', 'Create Account' %>
	<%= submit_tag "Generate Demo User", :class  => "btn-large demoButton" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LanguageLearningCommons</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="llcfill">
  <% if user_signed_in? %>
    <div class="header container">
        <div class="row">
          <div class="span4">
            <p class="text-center">
              <%= link_to current_user.name, user_url(current_user) if user_signed_in?%>
            <p>
          </div>
          <div class="span4">
            <p class="text-center">
              <%= link_to "Settings", edit_user_registration_url %>
            <p>
          </div>
          <div class="span4">
            <p class="text-center">
              <%= link_to "Sign out", destroy_user_session_url,
              :method => :delete if user_signed_in? %>
            <p>
          </div>
        </div>
    </div>
  <% end %>
  <div class="container llctext">
    <div class="titularRebuffed">
      <%= yield %>
    </div>
  </div>
  <% if current_user && current_user.demo %>
    <%= link_to note_demos_path, method: "POST" do %>
      <div class="note-demo-button demoButton">
        <b>
          Edit a Note
        </b>
      </div>
    <% end %>
  <% end %>
  <% if notice || alert %>
    <%= javascript_tag do %>
      $(LLC.popUp(<%= {"notice" => notice, "alert" => alert}.to_json.html_safe %>));
    <% end %>
  <% end %>
</body>
</html>

app/views/layouts/welcome.html.erb
<%= stylesheet_link_tag "bootstrap.css" %>
<%= stylesheet_link_tag "welcome.css" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<div class="welcome">
	<div class="welcome-title">
		Language Learning Commons
	</div>
	<div class="welcome-subtitle">
		<%= link_to "Luke Persola", "http://www.lukepersola.com/"%>'s capstone project at
		<%= link_to "App Academy", "http://www.appacademy.io/" %>
	</div>
	<div class="features">
		<table>
			<tr>
				<td class="feature-text">
					<div>Each user indicates which languages they are learning and which they can help others learn.</div>
				</td>
				<td class="feature-pic">
					<%= image_tag "LLC_featureImage1.png" %>
				</td>
			</tr>
			<tr>
				<td class="feature-text">
					<div>Fluid navigation makes it easy to <br /> find and connect to other users. <br /> Try clicking around.</div>
				</td>
				<td class="feature-pic">
					<%= image_tag "LLC_featureImage2.png" %>
				</td>
			</tr>
					<tr>
				<td class="feature-text">
					<div>Users can practice a language <br /> by publishing notes.</div>
				</td>
				<td class="feature-pic">
					<%= image_tag "LLC_featureImage3.png" %>
				</td>
			</tr>
			<tr>
				<td class="feature-text">
					<div>You can correct notes other users have published in languages you know. Highlight an excerpt and choose "revise" or "comment". </div>
				</td>
				<td class="feature-pic">
					<%= image_tag "LLC_featureImage4.png" %>
				</td>
			</tr>
			<tr>
				<td class="feature-text">
					<div>Hover over comments <br /> and revisions to reveal them. </div>
				</td>
				<td class="feature-pic">
					<%= image_tag "LLC_featureImage5.png" %>
				</td>
			</tr>
		</table>
		<br /><br /><br /><br /><br /><br /><br />
		Click the button below to try it out.
		<br /><br /><br /><br /><br />
	</div>
	<div class="tools">
		<div class="tool-text">
			<br />
			<b>About</b>
			<br /><br />
			This app was my capstone project at App Academy, which I attended in Spring 2013. It uses Rails and Devise to reproduce some basic social networking features, and JavaScript with some Backbone.js for the note commenting/revision functionality. I also used Twitter Bootstrap and the jQuery-color plugin.
			<br /><br />
		</div>
	</div>
	<div class="welcome-prompts-buffer"></div>
	<div class="welcome-prompts">
		<table>
			<tr>
				<td>
					<%= render :partial => "layouts/create_demo_user_button" %>
				</td>
				<td>
					<form action="<%= new_user_registration_url %>">
						<button class="btn-large">
							Sign Up
						</button>
					</form>
				</td>
				<td>
					<form action="<%= new_user_session_url %>">
						<button class="btn-large">
							Sign In
						</button>
					</form>
				</td>
			</tr>
		</table>
	</div>
</div>